### ISSUE TITLE
device not connected while realsense-viewer can show the device

### ISSUE THREAD

**Issue by monajalal** [Kaivalya192/live-pose#3]
Could you please help me with this error? `realsense-viewer` shows that the device is connected.

```
(my) root@DOS:/home/mona/live-pose# bash run_live.sh
Warp UserWarning: Python 3.9 or newer is recommended for running Warp, detected sys.version_info(major=3, minor=8, micro=19, releaselevel='final', serial=0)
Warp 1.3.3 initialized:
   CUDA Toolkit 12.5, Driver 12.5
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 3080 Laptop GPU" (16 GiB, sm_86, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.3.3
Traceback (most recent call last):
  File "interactive.py", line 23, in <module>
    mask_file_path = create_mask()
  File "/home/mona/live-pose/FoundationPose/learning/training/../../../FoundationPose/mask.py", line 28, in create_mask
    pipeline.start(config)
RuntimeError: No device connected
(my) root@DOS:/home/mona/live-pose# 
```

![Screenshot from 2024-09-17 17-43-29](https://github.com/user-attachments/assets/49a67abb-cd0e-40a5-942c-df63997ae7cb)

**Comment by monajalal** [comment]
Thanks a lot to Marty from Intel forum

Added `-v /dev:/dev` after `-v /dev/bus/usb:/dev/bus/usb` and now it is working.
